learning_hub/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'learning_hub'
urlpatterns = [
    # Home page.
    path('', views.index, name='index'),
    path('new_lesson/', views.new_lesson, name='new_lesson'), 
    path('filtered_lesson/', views.filtered_lesson, name='filtered_lesson'),
    path('filtered_lesson/lesson_delete/<int:id>', views.lesson_delete, name="lesson_delete"),
    path('filtered_lesson/lesson_detail/<int:pk>', views.lesson_detail , name='lesson-detail'), 
    path('search/', views.search, name="search"),
    path('result/', views.search, name="result"),    
    path('search/lesson_detail/<int:pk>', views.lesson_detail , name='lesson-detail'),
    #path('lessons/<int:pk>', views.lessons , name='lessons'),
    path('tokenizer/<int:id>/', views.tokenizer, name='tokenizer'),
    path('similarity/', views.similarity, name='similarity'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#urlpatterns += static('/filtered_lesson/learning_hub/media/', document_root=settings.STATIC_ROOT)
#urlpatterns += static('/search/lms_app/static/', document_root=settings.STATIC_ROOT)

lh_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('learning_hub.urls')),
    path('', include('pages.urls')), 
    path('', include('video.urls')),
]
#if settings.DEBUG:
    #urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('services/', views.services, name='services'),
]

learning_hub/models.py
from django.db import models

from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    class Meta:
        verbose_name_plural = "categories"
    name = models.CharField(max_length=100, null=True)
    def __str__(self):
        return str(self.name)
    
    
class Lesson(models.Model):
    title = models.CharField(max_length=100, unique=True)
    category = models.ForeignKey(Category, max_length=50, on_delete=models.CASCADE)
    keywords = models.CharField(max_length=200, blank=True)
    submitted = models.DateTimeField(auto_now_add=True)
    createdby = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    problem_statement = models.TextField(max_length=255, blank=True, null=True)
    problem_document = models.FileField(upload_to = "pdf", blank=False, null=True)
    answer_document = models.FileField(upload_to = "answer", blank=False, null=True)
    #problem_document = models.FileField(upload_to = 'static/pdf', blank=False)
    #answer_document = models.FileField(upload_to = 'static/pdf/answer', blank=False)
 
    def __str__(self):
        return str(self.id)
    
      
    

    
    
    

learning_hub/forms.py
from django import forms
from django.forms import TextInput

from .models import Lesson, Category

class LessonForm(forms.ModelForm):
    required_css_class = 'required'
    class Meta:
        model = Lesson
        fields = [
            'title', 'category', 'keywords', 'createdby', 'problem_document', 'answer_document', 
        ]
        widgets = {
            'title': TextInput(attrs={
                'class': "form-control",
                'style': 'max-width: 100%',
                'placeholder': 'Title'
                }),    
            'keywords': TextInput(attrs={
                'class': "form-control", 
                'style': 'max-width: 100%;',
                'placeholder': 'Enter keywords'
                })}

'''class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=200)
    file = forms.FileField()'''   

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Lesson
        fields = ['category',]
        validate = False




        
        
          

learning_hub/views.py
import string
from django.db import connection
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render

from lh_project import settings

from .models import Lesson, Category
from .forms import LessonForm, CategoryForm

import PyPDF2
from pydantic import FileUrl
import textract

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from pathlib import Path

from django.contrib import messages


# Create your views here.
def index(request):
    """The home page for Learning Hub."""
    return(render(request, 'learning_hub/base.html'))

@login_required
def filtered_lesson(request):
    form = CategoryForm(request.POST, request.FILES) 
    cat = request.POST.get('category') 

    lesson = Lesson.objects.all()
 
    if cat == None or cat == '':
        lesson_list = lesson
        category_name = "All"
    else:    
        lesson_list = lesson.filter(category__id=cat)
        category_name = Category.objects.filter(id=cat).values_list('name', flat=True).first()

    print("Category ID and name: ", cat, category_name)     
    #lesson_list = Lesson.objects.select_related('category').order_by('category')
    paginator = Paginator(lesson_list, settings.MAX_LESSON_LIST)  # Show 25 contacts per page.
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return render(request, "learning_hub/filtered_lesson.html", {"form": form, "page_obj": page_obj, "category_name": category_name})

'''def filtered_lesson(request):
    lesson = Lesson.objects.all()
    print("Lesson: ", lesson)
    return render(request, "learning_hub/filtered_lesson.html", {"lesson": lesson})'''
      
def new_lesson(request):
    #print(request)
    if request.method == 'POST':
        form = LessonForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            title = request.POST.get('title')
            id = getProblemStatementFromTitle(title)
            print("Id and Title: ", id[0][0], title)
            tokenizer(request, id[0][0])
        
            
            #return HttpResponseRedirect("/new_lesson/?submitted=true")
            return render(request, 'learning_hub/new_lesson.html', {'form': form, 'submitted': 'sumbitted'})
    else:
        form = LessonForm()
    return render(request, 'learning_hub/new_lesson.html', {'form': form})

def lesson_detail(request, pk):
    print("Request: ", request)
    lesson = Lesson.objects.get(pk=pk)
    context = {'lesson': lesson}
    return render(request, 'learning_hub/lesson_detail.html', context)

def getProblemStatementFromTitle(title):
    with connection.cursor() as cursor:
        cursor.callproc('getProblemStatementFromTitle', [title])
        results = cursor.fetchall()

    return results

def tokenizer(request, id):
    #lesson = Lesson()

    record = Lesson.objects.get(id=id)
        
    #context = {'entry': this_id, 'title': this_title, 'problem_statement': this_statement}
    #return render(request, 'base.html')
    record.problem_statement = (pdfTokenizer(id)).strip()
    record.save(update_fields=['problem_statement']) 
    
    #return HttpResponseRedirect('/lessons?submitted=True')
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def pdfTokenizer(id):
    print("Id = ", id)
    lesson = Lesson.objects.get(pk=id)
    print("BASE_DIR: ", settings.BASE_DIR)
    print("MEDIA_ROOT: ", settings.MEDIA_ROOT)
    print("STATICFILES_DIRS: ", settings.STATICFILES_DIRS)
    print("PDF doc name: ", lesson.problem_document)
    filename = str(settings.MEDIA_ROOT) + "/" + str(lesson.problem_document)
    print("File name: ", filename)
    
    #open allows you to read the file.
    pdfFileObj = open(filename,'rb')
        
    #The pdfReader variable is a readable object that will be parsed.
    pdfReader = PyPDF2.PdfReader(pdfFileObj)

    print('Number of pages = ',len(pdfReader.pages))

    #Discerning the number of pages will allow us to parse through all the pages.
    num_pages = len(pdfReader.pages)
    count = 0
    text = ""

    #The while loop will read each page.
    while count < num_pages:
        pageObj = pdfReader.pages[count]
        count += 1
        text += pageObj.extract_text()

    #print("Extracted text: ", text)    

    #This if statement exists to check if the above library returned words. It's done because PyPDF2 cannot read scanned files.
    if text != "":
        text = text
    #If the above returns as False, we run the OCR library textract to #convert scanned/image based PDF files into text.
    else:
        text = textract.process(FileUrl, method='tesseract', language='eng')

    #Now we have a text variable that contains all the text derived from our PDF file. Type print(text) to see what it contains. It likely contains a lot of spaces, possibly junk such as '\n,' etc.
    #Now, we will clean our text variable and return it as a list of keywords.

    #The word_tokenize() function will break our text phrases into individual words.
    #print("Extracted text: ", text)
    tokens = word_tokenize(text.lower())

    #We'll create a new list that contains punctuation we wish to clean.
    #punctuations = ['(',')',';',':','[',']',',']
    punctuations = [';',':','[',']',',','!','.',',','[',']']
    #We initialize the stopwords variable, which is a list of words like "The," "I," "and," etc. that don't hold much value as keywords.

    stop_words = stopwords.words('english')
    stop_words = set(stop_words)-set(['a'])

    #We create a list comprehension that only returns a list of words that are NOT IN stop_words and NOT IN punctuations.
    keywords = [word for word in tokens if not word in stop_words and not word in punctuations]
    #keywords = [word for word in tokens if not word in punctuations]
    #keywords = "Hello New World!"

    #print(keywords)
    keyword_collection = ' '
    for word in keywords:
        keyword_collection += ' ' + word
    return keyword_collection

def getProblemStatementFromTitle(title):
    with connection.cursor() as cursor:
        cursor.callproc('getProblemStatementFromTitle', [title])
        results = cursor.fetchall()

    return results

def getProblemStatement(id):
    with connection.cursor() as cursor:
        cursor.callproc('getProblemStatement', [id])
        results = cursor.fetchall()

    return results
    
def getLessonCount():
    with connection.cursor() as cursor:
        cursor.callproc('getLessonCount')
        results = cursor.fetchall()
        if results:  # Check if there are any results
            return results[0][0]  # Extract the number from the fetched results
        else:
            return None  # Return None if no results found

    print("Lesson count = ", results)
    return results

def getIdList():
    with connection.cursor() as cursor:
        cursor.callproc('getAllIds')
        results = cursor.fetchall()

    return results

def getCategory(id):
    with connection.cursor() as cursor:
        cursor.callproc('getCategory', [id])
        results = cursor.fetchall()

    return results


@login_required
def search(request):
    # Check if the request is a POST request (i.e., button click)
    if request.method == 'POST':
        dict_id = {}
        count = getLessonCount()
        print("Lesson count ", count)
        search_text = request.POST['search_text']  # Access the value of the "search_text" field from the submitted form
        print("Search text: ", search_text)
        if search_text is not "":
            dict_id = similarity(request, search_text)
            #dict_id = {0:87,1:76} #for testing with multiple ids
            print("Dict: ", dict_id)
        else:
            messages.add_message(request, messages.INFO, "Search box cannot be empty.")
            return render(request, 'error.html')

        if dict_id != {}:
            id_list = list(dict_id.values())

            lessons =  Lesson.objects.filter(id__in = id_list)
            context = {'lessons': lessons}
            return render(request, 'learning_hub/result.html', context)   
        else:
            messages.add_message(request, messages.INFO, "No matching questions found in LMS.")
            return render(request, 'learning_hub/error.html')
            #messages.error(request, "This is a custom message")
    #else:
         # Render the initial template if there was no button click
        #return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        
        #form = SearchForm()
        
    return render(request, 'learning_hub/search.html')

def calculateTermFrequency(tokens):
    # Calculate word frequency
    termFreq = {}
    # Iterate through the tokens and count the frequency of each token
    for token in tokens:
        if token in termFreq:
            termFreq[token] += 1
        else:
            termFreq[token] = 1
    return termFreq

def jaccard_similarity(set1, set2):
    # Calculate Jaccard similarity, which is a measure used to compare the similarity and diversity of sets
    intersection = set(set1).intersection(set2)
    union = set(set1).union(set2)
    similarity = len(intersection) / len(union)
    return similarity

def normalizeSimilarity(similarity):
    maxPossibleSimilarity = 1
    # Normalize the similarity score to a scale of 100 using a linear transformation
    confidence = (similarity * 100) / maxPossibleSimilarity
    return confidence

def similarity(request, search_text):
    context = {}
    kount = 0
    count = getLessonCount()
    idList = getIdList()

    for id in idList:
        conf = confidence(int(id[0]), search_text)
        print("MAX_CONFIDENCE: ", settings.MAX_CONFIDENCE)
        if conf > settings.MAX_CONFIDENCE:
            context[kount] = int(id[0])
            kount = kount + 1
        
    return context 
    
def confidence(id, search_text):

learning_hub/templates/learning_hub/base.html
{% load static %}

<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width-device-width initial-scale=1 shrink-to-fit=no">
        <link href="{% static '/main.css' %}" rel="stylesheet" type="text/css">

        {% load django_bootstrap5 %}
        {% bootstrap_css %}
        {% bootstrap_javascript %}

    </head>
    <body>
        <div class="p-3 mb-4 bg-light border rounded-3">
            <div class="container-fluid py-4">
                {% block title %}
                <title>Unlinked Document</title>
                {% endblock %}    
                <header id="header" style="width: 100%">
                    {% block header %}
                    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
                        <div class="container-fluid">    
                            <a href="{% url 'index' %}"><img src="{% static 'logo.png' %}" alt=""/></a>
                            <img class="img-fluid" src="{% static 'top_banner.jpeg' %}" alt=""/>
                            <span></span>
                        </div>
                        <div id="d-grid gap-2;" style="padding: 60px;">
                            <ul class="navbar-nav me-auto mb-2 mb-md-O;">
                                <li>
                                    {% if user.is_authenticated %}
                                        Hello, {{ user.username }}
                                        <form action="{% url 'logout' %}" method="post">
                                            {% csrf_token %}
                                            <button name="submit" class="btn btn-primary btn-sm;">Log&nbsp;out</button>
                                        </form>
                                        {% else %} 
                                            <!--<p>You are not logged in</p>-->
                                            <a class="btn btn-primary btn-sm;"
                                                href="{% url 'login' %}">Log&nbsp;in</a>
                                    {% endif %}   
                                </li>
                            </ul>
                            <span ></span>
                        </div>
                    </nav>
                    
                    {% endblock %}
                </header>  
                
                {% block sidebar %}
                    <aside id="leftsidebar" style="width: 14%">
                        <ul style="padding: 0cqb; list-style-type: none">
                            <li><a href="/">Learning Hub Home</a></li>
                            <li><a href="/about">About</a></li>
                            <li><a href="/services">Services</a></li>
                            <li><a href="/contact">Contact Us</a></li>
        
                            <li><a href="/filtered_lesson">Problems Database</a></li>
                            <li><a href="/search">Search Problems</a></li>
                            <li><a href="/video_list">Video Database</a></li>
                            {% if user.username == 'admin' %}
                            <li><a href="/new_lesson">Add Lesson</a></li>
                            <li><a href="/new_video">Add Video</a></li>
                            {% endif %}
                        </ul>  
                    </aside>
                {% endblock %}
                {% block main %}
                    <main id="main" style="width: 83%">
                        <h1 class="display-3">Welcome to Learning Hub</h1>
                        <p class="lead"> This portal helps you learn any topic you are interested in.</p>
                        Not a member? <a class="btn btn-primary btn-sm;"
                                href="{% url 'register' %}">Register &raquo;</a>    
                    </main>
                {% endblock %}
    
                {% block content %}{% endblock content %}
                <footer id="footer">Copyright &copy; 2023 LMS Web Design</footer>
    
        </div>
        </div>
   </body>
</html>

learning_hub/templates/learning_hub/error.html
{% extends "learning_hub/base.html" %}

{% block main %}
<section id="main" style="width: 80%">
    <h1>Error page</h1>
    {% if messages %}
    <section>
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    </section>
    {% endif %}
</section>
 


{% endblock %}

learning_hub/templates/learning_hub/filtered_lesson.html
{% extends "learning_hub/base.html" %}

{% load static %}

{% block main %}
<h1>Filter Lessons</h1>

{% if submitted %}
    <p class="success">
        The lesson was stored successfully. Thank you.
        {{ category_name }}
    </p>
{% else %}
    

    <div class="table-responsive">
        <table class="table table-sm" style="width: 100%">
            <thead>
                <tr>
                    <th colspan="7" style="text-align: right;">
                        <form action="" enctype="multipart/form-data" method="post" class="container needs-validation" novalidate>
                            <div class="table-responsive">
                                {% for field in form %}
                                    {{ field.label_tag }} {{ field }}
                                {% endfor %}
                                <input type="submit" value="Go" class="form-control-file"/>
                                {% csrf_token %}
                            </div>
                        </form>
                    </th>
                </tr>
                <tr><th colspan="7"><h3>Category: {{ category_name }}</h3></th></tr>
                <tr>
                    <th scope="col" style="width: 5%">ID</th>
                    <th scope="col" style="width: 33%">Title</th>
                    <th scope="col" style="width: 33%">Keywords</th>
                    <th scope="col" style="width: 8%">View</th>
                    <th scope="col" style="width: 8%">Details</th>
                    <th scope="col" style="width: 8%">Answer</th>
                    {% if user.username == 'admin' %}
                        <th scope="col" style="width: 5%">Delete</th>
                    {% endif %}    
                </tr>
            </thead>              
            {# {% for lesson in page_obj %} #}
            {% for x in page_obj %}
            {# Each "lesson" is a Lesson model object. #}
            <tbody>
                <tr>
                    <th scope="row">{{ x.id }}</th>
                    <td>{{ x.title|upper }}</td> 
                    <td>{{ x.keywords }}</td>
                    <td><a class="btn btn-secondary btn-sm;" href="{{ x.problem_document.url }}" role="button" target="_blank">Question</a></td>
                    <td><a class="btn btn-secondary btn-sm;" href="lesson_detail/{{ x.id }}" role="button">Details</a></td> 
                    <td><a class="btn btn-secondary btn-sm;" href="{{ x.answer_document.url }}" role="button" target="_blank">Answer</a></td>
                    {% if user.username == 'admin' %}
                        <td><a href="lesson_delete/{{ x.id }}"><img class="img-fluid" src="{% static 'delete_icon.png' %}" alt=""/></a></td>
                    {% endif %}
                </tr>
            </tbody>
            {% endfor %} 
        </table>   
    </div>

    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div> 
    
{% endif %}
{% endblock %}

learning_hub/templates/learning_hub/filtered_lesson1.html
{% extends "learning_hub/base.html" %}

{% block main %}
<h1>Problems Database</h1>   
<div class="container">
  {% for x in lesson %}
    <h3 class="text-center mt-2 mb-2">{{ x.title }}</h3>
      <a class="btn btn-secondary btn-sm;" href="{{ x.problem_document.url }}" role="button">View</a>
  {% endfor %}
</div>
{% endblock %}

learning_hub/templates/learning_hub/lesson_detail.html
{% extends "learning_hub/base.html" %}

{% load django_bootstrap5%}

{% block main %}
<section id="main" style="width: 80%"> 
    <h1>Lesson Details</h1>

    <table class="table table-striped">
        <tr><td style="width: 25%;">ID: </td><td>{{ lesson.id }}</td></tr>
        <tr><td style="width: 25%">Title: </td><td>{{ lesson.title }}</td></tr>
        <tr><td style="width: 25%">Created by: </td><td>{{ lesson.createdby }}</td></tr>
        <tr><td style="width: 25%">Keywords: </td><td>{{ lesson.keywords }}</td></tr>
        <tr><td style="width: 25%">Created on: </td><td>{{ lesson.submitted }}</td></tr>
        <tr style="max-height: 50pt; margin:auto;"><td colspan="2">
            Problem:
        </td></tr> 
        <tr>
            <td colspan="2">
                <div class="form-group">
                    <textarea class="container-fluid" id="exampleFormControlTextarea1" rows="3">
                        {{ lesson.problem_statement }}
                    </textarea>
                </div>                    
            </td>
        </tr>
  
    </table>
</section>


{% endblock %}

learning_hub/templates/learning_hub/lessons.html
{% extends "base.html" %}

{% load django_bootstrap5%}

{% block main %}

    <section id="main" style="width: 81%"> 
        <h1>All Lessons</h1>

       
             
        <div class="table-responsive">
            <table class="table table-sm" style="width: 100%">
                <thead>
                    <tr>
                        <th scope="col" style="width: 5%">ID</th>
                        <th scope="col" style="width: 30%">Title</th>
                        <th scope="col" style="width: 10%">Category</th>
                        <th scope="col" style="width: 31%">Keywords</th>
                        <th scope="col" style="width: 8%">View</th>
                        <th scope="col" style="width: 8%">Details</th>
                        <th scope="col" style="width: 8%">Answer</th>
                    </tr>
                </thead>              
                {% for lesson in page_obj %}
                {# Each "lesson" is a Lesson model object. #}
                <tbody>
                    <tr>
                        <th scope="row">{{ lesson.id }}</th>
                        <td>{{ lesson.title|upper }}</td> 
                        <td>{{ lesson.category.name }}</td>
                        <td>{{ lesson.keywords }}</td>
                        <td><a class="btn btn-secondary btn-sm;" href="{{ lesson.problem_document }}" role="button" target="_blank">Question</a></td>
                        <td><a class="btn btn-secondary btn-sm;" href="lesson_detail/{{ lesson.id }}" role="button">Details</a></td> 
                        <td><a class="btn btn-secondary btn-sm;" href="{{ lesson.answer_document }}" role="button" target="_blank">Answer</a></td>
                    </tr>
                </tbody>
                {% endfor %} 
            </table>   
        </div>

        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div> 
    </section>   
{% endblock %}

learning_hub/templates/learning_hub/new_lesson.html
{% extends "learning_hub/base.html" %}

{% block main %}
<h1>Upload Lessons</h1>

{% if submitted %}
    <p class="success">
        The lesson was stored successfully. Thank you.
        {{ category.name }}
    </p>
{% else %}
    <div class="mb-3 form-check">
        <form action="" enctype="multipart/form-data" method="post" novalidate>
            <div class="table-responsive">
                <table class="table">
                    {{ form.as_table }}
                    <tr>
                        <td scope="row" width="25%">&nbsp;</td>
                        <td><input type="submit" value="Submit" class="form-control-file"></td>
                    </tr>
                </table>
                    {% csrf_token %}
            </div>
        </form>
    </div>
{% endif %}
{% endblock %}

learning_hub/templates/learning_hub/search.html
{% extends "learning_hub/base.html" %}

{% block main %}
<section id="main" style="width: 80%">
    <h1>Search</h1>

    {% if submitted %}
    <p>
        Your message was submitted successfully. Thank you.
    </p>
    {% else %}
    <div class="mb-3 form-check">
        <form action="" enctype="multipart/form-data" method="post" novalidate>
            <div class="table-responsive">
                <!--Table-->
                <table class="table table-striped">
                    <tr>
                        <td colspan="2">
                            <div class="container-fluid">
                                <ul>
                                    <li>
                                        Enter your question or a related keyword in the search field.
                                    </li>
                                    <li>
                                        Click "Search".
                                    </li>
                                    <li>
                                        If your question exists in the database, you'll be redirected 
                                        to the answer screen.
                                    </li>
                                    <li>
                                       If not, your question will be sent to the instructors and they 
                                        will upload an answer within a day.
                                    </li> 
                                </ul> 
                                Remember that our instructors are working to provide you with the information you need as quickly as possible. 
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <form action="{% url 'learning_hub:search' %}" method="post" class="row g-3 needs-validation">
                                {% csrf_token %}
                                <div class="form-group">
                                    <textarea class="form-control" type="text" name="search_text" id="search_text" rows="10" style="font-size: 14px!important;"></textarea>      
                                    <input type="submit" value="Search" class="btn btn-primary btn lg mt-1" required/>
                                </div>
                            </form>
                        </td>
                    </tr>
                </table>
            </div>
            {% csrf_token %}
        </form>
        {% endif %}
    </div>
</section> 
{% endblock %}